version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"

  online.contact:
    build: .
    container_name: online.contact
    image: online.contact:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DATABASE=online_contact
    expose:
      - "8080"
