version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"

  online.contact:
    build: .
    container_name: online.contact
    image: online.contact:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=online_contact
      - JWT_SECRET=9b3fe23b471c74792f4f730e38449cd34a4184796c73bdba0381f7301c62d657
    expose:
      - "8080"
